### PR TITLE
Fix batch not saving the last machineData properly

### LINKED ISSUE #138: Produced amount
The produced amount is never updated to actual amount - see the below picture.

### PR DESCRIPTION
**Pull request by Lawst96**
Closes #138 

## Description
Subscription had a minor bug where the batch might not save the latest machineData properly. That should be fixed now with a change to when the Batch is cleared.

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes, if necessary.
- [x] All tests pass (existing and potential new).
- [x] Sonar check has passed
- [x] No codesmells or bugs

## Other Relevant Information
Provide any other important details below.

### CODE REVIEW

**Review by Kaszz — APPROVED** [review]

File: BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java [hunk 1]
```diff
@@ -222,6 +217,12 @@ else if (AdminNodes.BATCH_PRODUCT_ID.nodeId.toParseableString().equals(id) && cu
 
         if (this.currentBatch != null) {
             this.saveBatch();
+
+            // if state is == 17 remove the object reference.
```
Comment (Kechr) [inline BrewMesModulesParent/subscriber/src/main/java/com/brewmes/subscriber/Subscription.java:221]:
```suggestion
            // if state == 17, 9 or 2, remove the object reference.
```

**Review by Kechr — CHANGES_REQUESTED** [review]

**Review by Teyson — APPROVED** [review]

**Review by Kechr — APPROVED** [review]
