### PR TITLE
Fixed oee and added rounding to all relevant values

### LINKED ISSUE #156: OEE not input correctly in PDF
OEE is not input correctly in PDF report

### PR DESCRIPTION
**Pull request by Kaszz**
Closes #156 

## Description
Fixed the OEE

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes, if necessary.
- [x] All tests pass (existing and potential new).
- [x] Sonar check has passed
- [x] No codesmells or bugs

## Other Relevant Information
Provide any other important details below.

### CODE REVIEW

File: BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/DataOverTime.java [hunk 1]
```diff
@@ -15,6 +19,15 @@
     private double minHumidity;
     private double maxHumidity;
 
+    public static double round(double value, int places) {
+        if (places < 0) throw new IllegalArgumentException();
```
Comment (Teyson) [inline BrewMesModulesParent/batch/src/main/java/com/brewmes/batch/DataOverTime.java:23]:
```suggestion
        if (places < 0) {
        throw new IllegalArgumentException();
        }
```

**Review by Kechr — CHANGES_REQUESTED** [review]
image

**Comment by Kechr** [comment]
image

**Review by Wylardt — APPROVED** [review]

**Review by dottore1 — APPROVED** [review]

**Review by Teyson — APPROVED** [review]

**Review by Lawst96 — APPROVED** [review]

**Review by Kechr — APPROVED** [review]
